### PR TITLE
Modernize the entire sample

### PR DESCRIPTION
**Pull request by rykoma**
The sample code is old and using very old NuGet packages. We need to update entire code so that to work with the latest packages.

I did the followings:

- Change Target framework to .NET Framework 4.7.2
- Update all NuGet packages and fix code issues so that to use the latest modules
- Update ReadMe.md

### CODE REVIEW

**Comment by rykoma** [comment]
@jasonjoh @Rick-Kirkham 

Do you know who is responsible for PRs of this repo? Or, could you review and merge this PR, please?

**Comment by jasonjoh** [comment]
I haven't worked with Outlook add-ins for a few years now. @Rick-Kirkham can you help here?

**Comment by Rick-Kirkham** [comment]
@davidchesnut is now our auth/SSO man.

**Comment by rykoma** [comment]
@davidchesnut
Could you please review this PR?

**Review by davidchesnut — APPROVED** [review]
This is great!

**Pull request merged**
